import { StyleSheet } from "react-native";

export const color=StyleSheet.create({
    backgroundPrimary:{
        backgroundColor:'#fff'
    },
    backgroundSecondary:{
        backgroundColor:'#F5F5F5'
    },
    backgroundTertiary:{
        backgroundColor:'#495057'
    },
    backgroundAccent:{
        backgroundColor:'#212429'
    },
    contentPrimary:{
        color:'#212429',
        fontFamily:'Inter'
    },
    contentSecondary:{
        color:'#868D94'
    },
    contentTertiary:{
        color:'#B0B5B9'
    },
    contetAccent:{
        color:'#212429'
    },
    contentStateDisabled:{
        color:'#C9CCCF'
    },
    contentOnColorInverse:{
        color:'#fff'
    },
    contentSale:{
        color:'#FA254C'
    }
})

export const sizes=StyleSheet.create({
    heading1:{
        fontSize:32,
        fontWeight:'600',
    },
    heading2:{
        fontSize:20,
    },
    heading3:{
        fontSize:14,
    },
    body1:{
        fontSize:14,
        fontWeight:'400'
    },
    body2:{
        fontSize:12
    },
    body3:{
        fontSize:16
    },
    caption1:{
        fontSize:10
    },
    caption2:{
        fontSize:10,
        fontWeight:'600'
    }
})

export const layout=StyleSheet.create({
    rowCenter:{
        display:'flex',
        flexDirection:'row',
        alignItems:'center',
        justifyContent:'center'
    },
    rowSpaceBetween:{
        display:'flex',
        flexDirection:'row',
        alignItems:'center',
        justifyContent:'space-between'
    },
    rowSpaceAround:{
        display:'flex',
        flexDirection:'row',
        alignItems:'center',
        justifyContent:'space-around'
    },
    rowSpaceEvenly:{
        display:'flex',
        flexDirection:'row',
        alignItems:'center',
        justifyContent:'space-evenly'
    },
    columnCenter:{
        display:'flex',
        flexDirection:'column',
        alignItems:'center',
        justifyContent:'center'
    },
    columnSpaceBetween:{
        display:'flex',
        flexDirection:'column',
        alignItems:'center',
        justifyContent:'space-between'
    },
    columnSpaceAround:{
        display:'flex',
        flexDirection:'column',
        alignItems:'center',
        justifyContent:'space-around'
    },
    columnSpaceEvenly:{
        display:'flex',
        flexDirection:'column',
        alignItems:'center',
        justifyContent:'space-evenly'
    }
})